FROM sinzlab/pytorch:v3.8-torch1.4.0-cuda10.1-dj0.12.4
    
RUN pip3 install neuralpredictors
RUN pip3 install git+https://github.com/sinzlab/nnfabrik.git@e71c01f2326c2027651357de433b09191d6057c1

WORKDIR /notebooks


